name: Add IF score and update README.md
on: [push]
jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2
            - name: Update README
              run: |
                FILE_PATH="./README.md"
                SVG_STRING='
                  <image
                    width="65"
                    height="65"
                    src="https://if.greensoftware.foundation/img/logo.svg">
                  <span style="color:#006d69">*Carbon Embodied: 0.35 gCO2eq/s*</span>
                '
                echo "$SVG_STRING" >> $FILE_PATH
            - name: Config global git user
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: git config --global user.name "${{ github.actor }}"
            - name: Commit and push
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
               git checkout -b readme-update-workflow-5
               git add README.md
               git commit -m "IF score label"
               git push origin readme-update-workflow-5
