name: Update README
on: [push]
jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2
            - name: Update README
              run: |
                FILE_PATH="./README.md"
                SVG_STRING='
                  <image
                    width="128"
                    height="50"
                    src="https://if.greensoftware.foundation/img/logo.svg">
                  <font style="color:#006d69">Carbon Embodied: 0.35 gCO2eq/s</font>
                '
                echo "$SVG_STRING" >> $FILE_PATH
            - name: Commit and Push Changes
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
               git config --global user.name "${{ github.actor }}"
               git config --global user.email "${{ github.actor }}@users.noreply.github.com"
               git checkout -b readme-update-workflow-2
               git add README.md
               git commit -m "added IF score label to docs list"
               git push origin readme-update-workflow-2
