name: Update README
on: [push]
jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2
            - name: Update README
              run: |
                FILE_PATH="./README.md"
                IMG_STRING='
                    <dl>
                      <image
                        width="65"
                        height="65"
                        src="https://if.greensoftware.foundation/img/logo.svg">
                      <dd>
                        <span style="color:#green">Carbon Embodied: 0.35 gCO2eq/s*</span>
                      </dd>
                    </dl>
                '
                echo "IMG_STRING" >> $FILE_PATH
            - name: Commit and Push Changes
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
               git config --global user.name "${{ github.actor }}"
               git config --global user.email "${{ github.actor }}@users.noreply.github.com"
               git add README.md
               git commit -m "added IF score label to docs list"
               git push origin main
