name: Update README
on: [push]
jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2
            - name: Update README
              run: |
                FILE_PATH="./README.md"
                IMG_STRING='
                      <image
                        width="65"
                        height="65"
                        src="https://if.greensoftware.foundation/img/logo.svg">
                    <dl>
                      <dd>
                        <span style="color:#green">Carbon Embodied: 0.35 gCO2eq/s*</span>
                      </dd>
                    </dl>
                '
                echo $IMG_STRING >> $FILE_PATH
            - name: Extract branch name
              shell: bash
              run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" 
              id: extract_branch
            - name: Commit and Push Changes
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
               git config --global user.name "${{ github.actor }}"
               git config --global user.email "${{ github.actor }}@users.noreply.github.com"
               git add README.md
               git commit -m "IF score label was added to README.md"
               git push origin ${{ steps.extract_branch.outputs.branch }}
               